traits:
- trait_id: IBS
  trait_label: Irritable bowel syndrome
  ancestry: EUR
  sample_size: 10000
  build: GRCh38
  file_path: tests/data/smoke/ibs_summary.smoke.tsv.gz
  is_mandatory: true
  beta_col: beta
  se_col: se
  p_col: p
  ea_col: effect_allele
  oa_col: other_allele
  chr_col: chr
  pos_col: pos
  rsid_col: rsid
- trait_id: MDD
  trait_label: Major depressive disorder
  ancestry: EUR
  sample_size: 10000
  build: GRCh38
  file_path: tests/data/smoke/mdd_summary.smoke.tsv.gz
  is_mandatory: true
  beta_col: beta
  se_col: se
  p_col: p
  ea_col: effect_allele
  oa_col: other_allele
  chr_col: chr
  pos_col: pos
  rsid_col: rsid
- trait_id: ANXIETY
  trait_label: Anxiety
  ancestry: EUR
  sample_size: 10000
  build: GRCh38
  file_path: tests/data/smoke/anxiety_summary.smoke.tsv.gz
  is_mandatory: true
  beta_col: beta
  se_col: se
  p_col: p
  ea_col: effect_allele
  oa_col: other_allele
  chr_col: chr
  pos_col: pos
  rsid_col: rsid
- trait_id: NEUROTICISM
  trait_label: Neuroticism
  ancestry: EUR
  sample_size: 10000
  build: GRCh38
  file_path: tests/data/smoke/neuroticism_summary.smoke.tsv.gz
  is_mandatory: true
  beta_col: beta
  se_col: se
  p_col: p
  ea_col: effect_allele
  oa_col: other_allele
  chr_col: chr
  pos_col: pos
  rsid_col: rsid
